### ISSUE TITLE
Orthpol-light installation error

### ISSUE THREAD

**Issue by SebastianGonzalez2000** [MarineRoboticsGroup/NF-iSAM#4]
I have tried installing TransportMaps on my Mac in various different ways including automatic installation and manual installation. However, I always run into the following error: 

```
`Collecting orthpol-light>=1.0.1 (from transportmaps==3.0.8)
  Using cached orthpol_light-1.0.1.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]`
```
I have installed all three requirements successfully:

`brew install llvm
brew install gfortran
brew install open-mpi`

But when I try the command `pip install --upgrade TransportMaps` I get the following stack trace:
```
`Processing /Users/sebastiangonzalez/Desktop/TransportMap-Experiments/transportmaps
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from transportmaps==3.0.8)
  Obtaining dependency information for click from https://files.pythonhosted.org/packages/1a/70/e63223f8116931d365993d4a6b7ef653a4d920b41d03de7c59499962821f/click-8.1.6-py3-none-any.whl.metadata
  Using cached click-8.1.6-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: numpy>=1.15 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transportmaps==3.0.8) (1.25.2)
Collecting orthpol-light>=1.0.1 (from transportmaps==3.0.8)
  Using cached orthpol_light-1.0.1.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4_/nzz34mw92z95d1z69bt863cm0000gn/T/pip-build-env-de3p63fy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4_/nzz34mw92z95d1z69bt863cm0000gn/T/pip-build-env-de3p63fy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4_/nzz34mw92z95d1z69bt863cm0000gn/T/pip-build-env-de3p63fy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4_/nzz34mw92z95d1z69bt863cm0000gn/T/pip-build-env-de3p63fy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 20, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`
```

I have not been able to find help anywhere else. I would appreciate any ideas on what could be going wrong. Cheers.

**Comment by alanpapalia** [comment]
Hey Sebastian, it seems like you've already looked at https://github.com/MarineRoboticsGroup/NF-iSAM/issues/1#issuecomment-1079750416 and tried to best follow steps (albeit for Ubuntu, not Mac)? Can you quickly verify that?

We're a little busy now (@doublestrong is defending his thesis tomorrow!) and we don't have many Macs laying around but if none of this works we can try to get a hold of a Mac and report back with our results.

Can you give the full details of your system to the best of your abilities (OS, fresh conda environment, etc)? It'd be useful to know exactly every command you ran to try to set things up.

**Comment by SebastianGonzalez2000** [comment]
Thanks for the quick response! This is my current setup:

> macOS Big Sur 11.7.7
> Fresh virtual environment

Commands:
0) Create virtualenv
```
python -m venv TRANSPORT_MAPS
source TRANSPORT_MAPS/bin/activate
```

1) Install Requirements
```
brew install llvm
brew install gfortran
brew install open-mpi
```

2) Upgrade pip
`pip install --upgrade pip`

3) Install dependencies
`pip install --upgrade numpy cython`

4) Attempt to install TransportMaps (This is where I get the error)
`pip install --upgrade TransportMaps`

**Comment by alanpapalia** [comment]
Can you try to build a `conda` environment from the `environment.yml` file?

```
cd NF-iSAM
conda env create -f environment.yml
conda activate NFiSAM
pip3 install --upgrade TransportMaps
```

You may also have some success actually reaching out to the TransportMaps team, as it seems they're actively maintaining the package. (Not trying to push you elsewhere, just they may be more useful :) )

**Comment by SebastianGonzalez2000** [comment]
Are all dependencies in the environment.yml file intended to work on a Mac? These packages are causing some errors:

> conda env create -f environment.yml

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - xz==5.2.5=h7b6447c_0
  - brotlipy==0.7.0=py39h27cfd23_1003
  - setuptools==58.0.4=py39h06a4308_0
  - conda-package-handling==1.7.3=py39h27cfd23_1
  - libffi==3.3=he6710b0_2
  - ca-certificates==2021.10.26=h06a4308_2
  - sqlite==3.37.0=hc218d9a_0
  - pysocks==1.7.1=py39h06a4308_0
  - cryptography==36.0.0=py39h9ce1e76_0
  - tk==8.6.11=h1ccaba5_0
  - certifi==2021.10.8=py39h06a4308_2
  - openssl==1.1.1m=h7f8727e_0
  - cffi==1.15.0=py39hd667e15_1
  - ld_impl_linux-64==2.35.1=h7274673_9
  - _openmp_mutex==4.5=1_gnu
  - pip==21.2.4=py39h06a4308_0
  - zlib==1.2.11=h7f8727e_4
  - libstdcxx-ng==9.3.0=hd4cf53a_17
  - python==3.9.7=h12debd9_1
  - pycosat==0.6.3=py39h27cfd23_0
  - yaml==0.2.5=h7b6447c_0
  - ncurses==6.3=h7f8727e_2
  - ruamel_yaml==0.15.100=py39h27cfd23_0
  - libgomp==9.3.0=h5101ec6_17
  - conda==4.11.0=py39h06a4308_0
  - readline==8.1.2=h7f8727e_1
  - libgcc-ng==9.3.0=h5101ec6_17
```

Note: I have tried contacting the TransportMaps team but they I have found them hard to reach through their Q2A page.

**Comment by daniele-bigoni** [comment]
Hi, I'm the maintainer of TransportMaps. I take the conversation with Sebastian here.

Sorry for the Q&A, we should take offline the Q&A because it has been plagued with spam for a while.

Regarding your issue. Which version of TransportMaps are you trying to install?

It seems you are trying to install orthpol 1.0.1
That version required quite some work to get it working on macOS. 

The new version 2.0.2 should install more easily but I don't know which dependencies are blocking you from upgrading.

**Comment by SebastianGonzalez2000** [comment]
Hello @daniele-bigoni and @alanpapalia. I decided to work on an Ubuntu 22.04.3 machine instead. Thanks for the help.

**Comment by doublestrong** [comment]
Thanks, @alanpapalia and @daniele-bigoni, for the help. I just noticed this issue. Good luck @SebastianGonzalez2000. Let us know how we can help. I haven't tried orthpol 2.0.2, but I think it should still work for our code. We are just using TransportMaps to define probability distributions.
